### PR TITLE
Switch to cross-compilation for `linux_aarch64` and `linux_ppc64le`

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hoping to use fewer ARM runners since they appear to be failing in #25.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by bdice** [comment]
I took a quick review of the diff and I think this is good to go!

**Comment by jakirkham** [comment]
Agreed. Thanks Bradley! 🙏

**Pull request merged**
